### PR TITLE
Add option to enable JIT support

### PR DESCRIPTION
**Pull request by msteinert**

### CODE REVIEW

**Comment by uilianries** [comment]
Is there any external requirement to use JIT option?

**Comment by msteinert** [comment]
No, it's all internal to PCRE.

**Comment by msteinert** [comment]
If you're curious there is some explanation here:

https://www.pcre.org/original/doc/html/pcrejit.html

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
@msteinert Thanks!

**Pull request merged**
